sudo: false
language: c
cache:
  directories:
  - "$HOME/.ghc"
  - "$HOME/.cabal"
  - "$HOME/.stack"
matrix:
  include:
  - env: BUILD=stack ARGS="--resolver lts-5"
    compiler: ": #stack 7.10.3"
    addons:
      apt:
        packages:
        - ghc-7.10.3
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons:
      apt:
        packages:
        - libgmp-dev
  allow_failures:
  - env: BUILD=cabal GHCVER=head  CABALVER=head
  - env: BUILD=stack ARGS="--resolver nightly"
before_install:
- unset CC
- CABALARGS=""
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  case "$BUILD" in
    stack)
      stack --no-terminal --install-ghc $ARGS test --only-dependencies
      ;;
    cabal)
      cabal --version
      travis_retry cabal update
      cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS
      ;;
  esac
script:
- |
  case "$BUILD" in
    stack)
      stack --no-terminal $ARGS test --haddock --no-haddock-deps --ghc-options="-Wall -fno-warn-unused-do-bind -Werror"
      ;;
    cabal)
      cabal configure --enable-tests --enable-benchmarks -v2 --ghc-options="-O0 -Werror"
      cabal build
      cabal check || [ "$CABALVER" == "1.16" ]
      cabal test
      cabal copy
      # cabal sdist fails on cabal 1.16:
      cabal sdist || [ "$CABALVER" == "1.16" ]
      SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && \
        (cd dist && cabal install --enable-tests --force-reinstalls "$SRC_TGZ" || \
            [ "$CABALVER" == "1.16" ])
      ;;
  esac
before_deploy:
- stack install
deploy:
  provider: releases
  api_key:
    secure: cOmabNnVtxq+j+ZXvwW6uAoSlSMS4DG14f7K3uweIss1FfoDQaeHL/0w+EhYJNDh2HX3KwSNDQEvJDyJYlPgp4iKqCG0U+nl/h/do2AUXLmWSNPBvRoE5/76XQjLAv+4Cg+i62MlcMESItNcLDTaCvYVwCItZltBo9f47NDFBNDW/sRhBzOm62OAdoaEXtJ5RcGqceJL0eUTCPxSHAHS6X14jA8lInsz1pCsZkeCodpvDVXbji4ZDDiLZnzPynrK67wwSz0sX4AuQtk6XSytg6ffBLbRolUFsGSRC9Mv4XWG4ukvzKxvClbb18PvAPzYC1Av6LuvctQOASr93IUldksBc+sMGRrC9KKIos5WAe6qLYq2LppyU6w7xISTl6VWKO9TUxS4OTcC5fL2AYtQyRwNhV0nm9fo9fH2h8q11uNMPTz+e8AuyjwvO8mXLA6B8UPHe0B3hz52JVFFfdaRAzpmEcF2KRq/RL+UmATSG2WZSkoWNI3T+E8F+QBWJ5/so7RGZpyoi+8LgPFuCn2tACc0HorG5K7/qMF8l1vmkRiSGaJyaRvDPLm4hwHi1lUstivnAqbZ8cUBuGMzRnwvK+PTPJmBDQol8oHKMb/IxEBrenbPO2X0keZJ9nLPeszka1/1yqzEuB84OgxKif9pNSRnrcba/k51rLFkIRMzKpQ=
  file: "$HOME/.local/bin/spock-hello-exe"
  on:
    repo: eiel/spock-hello
    tags: true
